blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/rbwtech/easy-to-you-automation/blob/main/README.md
    about: Check our comprehensive documentation first
  - name: 💬 GitHub Discussions
    url: https://github.com/rbwtech/easy-to-you-automation/discussions
    about: Ask questions and discuss with the community
  - name: 📧 Email Support
    url: mailto:radipta111@gmail.com
    about: Contact maintainer directly for private matters
