name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Easy-To-You Automation ${{ github.ref }}
          body: |
            🚀 **Easy-To-You Automation Release**

            Professional IonicCube decoder with enhanced performance and reliability.

            ## 🎯 Quick Start
            ```bash
            git clone https://github.com/rbwtech/easy-to-you-automation.git
            cd easy-to-you-automation
            pip install -r requirements.txt
            python scripts/main.py -u USERNAME -p PASSWORD -s ./source -o ./output -v
            ```

            ## 📖 Documentation
            - [Installation Guide](https://github.com/rbwtech/easy-to-you-automation/blob/main/docs/installation.md)
            - [Usage Examples](https://github.com/rbwtech/easy-to-you-automation/blob/main/docs/usage.md)
            - [Troubleshooting](https://github.com/rbwtech/easy-to-you-automation/blob/main/docs/troubleshooting.md)

            Full changelog: [CHANGELOG.md](https://github.com/rbwtech/easy-to-you-automation/blob/main/CHANGELOG.md)
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/
          asset_name: easy-to-you-automation-dist
          asset_content_type: application/zip
